const fs = require('fs');
const file = 'c:/Main-Projects/recipe-generator-client/src/components/Banner.tsx';
let code = fs.readFileSync(file, 'utf8');

const s4vStart = code.indexOf('function Slide4Visual() { // hero5.png - Ingredient Rescue');
const s4vEnd = code.indexOf('\nconst VISUALS = [', s4vStart);

if (s4vStart === -1 || s4vEnd === -1) {
  console.log('Could not find bounds! s4vStart=' + s4vStart + ' s4vEnd=' + s4vEnd);
  process.exit(1);
}

// Build the new function as an array of lines, then join — avoids template literal escaping issues
const lines = [
  'function Slide4Visual() { // hero5.png - AI Meal Planner + Smart Matcher',
  '  const weekPlan = [',
  '    { day: "Mon", meal: "Chicken Bowl",  cost: "$120" },',
  '    { day: "Tue", meal: "Veg Pasta",     cost: "$100" },',
  '    { day: "Wed", meal: "Grilled Fish",  cost: "$150" },',
  '  ];',
  '',
  '  return (',
  '    <div className="relative w-full h-full pointer-events-none hidden xl:flex items-center justify-end pr-4 2xl:pr-8">',
  '',
  '      {/* ── Fixed-width composition container ── */}',
  '      <div className="relative w-[560px] xl:w-[600px] 2xl:w-[640px] h-full flex items-center justify-center">',
  '',
  '        {/* ── Card 1: AI Meal Planner (top-left of composition) ── */}',
  '        <motion.div',
  '          className="absolute left-[10px] top-[8%] z-30 w-[230px] bg-white/95 dark:bg-slate-900/95 backdrop-blur-md rounded-3xl shadow-2xl border border-stone-100 dark:border-slate-700/60 p-4 pointer-events-auto"',
  '          initial={{ opacity: 0, x: -20, y: -10 }}',
  '          animate={{ opacity: 1, x: 0, y: [0, -5, 0] }}',
  '          transition={{ opacity: { delay: 0.3, duration: 0.6 }, x: { delay: 0.3, duration: 0.5 }, y: { delay: 1.0, duration: 5.5, repeat: Infinity, ease: "easeInOut" } }}',
  '        >',
  '          <div className="flex items-center gap-2.5 mb-3 pb-3 border-b border-stone-100 dark:border-slate-800">',
  '            <div className="w-8 h-8 rounded-xl bg-emerald-600 flex items-center justify-center text-white shadow-sm shrink-0">',
  '              <Calendar size={14} />',
  '            </div>',
  '            <div>',
  '              <p className="text-[13px] font-black text-stone-900 dark:text-white leading-none">AI Meal Planner</p>',
  '              <p className="text-[9px] text-stone-400 mt-0.5">Plan weekly meals with your budget.</p>',
  '            </div>',
  '          </div>',
  '          <div className="space-y-2 mb-3">',
  '            {weekPlan.map((item, i) => (',
  '              <div key={i} className="flex items-center gap-2">',
  '                <div className={["w-5 h-5 rounded-md flex items-center justify-center shrink-0 text-white text-[9px] font-bold", i === 0 ? "bg-emerald-600" : "bg-stone-200 dark:bg-slate-700"].join(" ")}>',
  '                  {i === 0 ? <Check size={10} /> : <span className="text-stone-500 dark:text-slate-400">{i+1}</span>}',
  '                </div>',
  '                <span className="flex-1 text-[10px] font-semibold text-stone-700 dark:text-slate-200 truncate">{item.meal}</span>',
  '                <span className="text-[10px] font-bold text-emerald-700 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-900/20 px-1.5 py-0.5 rounded-lg shrink-0">{item.cost}</span>',
  '              </div>',
  '            ))}',
  '          </div>',
  '          <div className="flex items-center justify-between bg-stone-50 dark:bg-slate-800 rounded-xl px-3 py-2">',
  '            <span className="text-[10px] text-stone-500 dark:text-slate-400">Weekly budget</span>',
  '            <span className="text-[11px] font-black text-emerald-700 dark:text-emerald-400">$370 / $400</span>',
  '          </div>',
  '        </motion.div>',
  '',
  '        {/* ── Card 2: Smart Meal Matcher (center-right) ── */}',
  '        <motion.div',
  '          className="absolute right-[12px] top-[35%] z-30 w-[220px] bg-white/95 dark:bg-slate-900/95 backdrop-blur-md rounded-3xl shadow-2xl border border-stone-100 dark:border-slate-700/60 p-4 pointer-events-auto"',
  '          initial={{ opacity: 0, x: 20, y: 10 }}',
  '          animate={{ opacity: 1, x: 0, y: [0, 5, 0] }}',
  '          transition={{ opacity: { delay: 0.55, duration: 0.6 }, x: { delay: 0.55, duration: 0.5 }, y: { delay: 1.2, duration: 6, repeat: Infinity, ease: "easeInOut" } }}',
  '        >',
  '          <div className="w-10 h-10 rounded-xl mb-3 flex items-center justify-center overflow-hidden shadow-sm bg-gradient-to-br from-emerald-500 via-indigo-500 to-amber-400">',
  '            <Smile size={18} className="text-white" />',
  '          </div>',
  '          <p className="text-[13px] font-black text-stone-900 dark:text-white leading-tight mb-1">Smart Meal Matcher</p>',
  '          <p className="text-[10px] text-stone-400 dark:text-slate-400 leading-snug mb-4">Based on your profile, you might like:</p>',
  '          <div className="bg-emerald-50 dark:bg-emerald-900/20 rounded-xl px-3 py-2.5 mb-3 border border-emerald-100 dark:border-emerald-800/40">',
  '            <p className="text-[11px] font-bold text-stone-800 dark:text-white leading-snug">Spicy Lentil Soup.</p>',
  '            <p className="text-[9px] text-emerald-600 dark:text-emerald-400 font-medium mt-0.5">98% match · 420 kcal</p>',
  '          </div>',
  '          <button className="w-full bg-emerald-600 hover:bg-emerald-700 text-white text-[11px] font-bold py-2.5 rounded-xl transition-colors pointer-events-auto shadow-sm">',
  '            View Full Plan',
  '          </button>',
  '        </motion.div>',
  '',
  '        {/* ── Decorative leaf: top-left ── */}',
  '        <motion.div',
  '          className="absolute left-[5%] top-[5%] z-20 pointer-events-none"',
  '          initial={{ opacity: 0, rotate: -15 }}',
  '          animate={{ opacity: 1, rotate: [-15, -10, -15], y: [0, 6, 0] }}',
  '          transition={{ opacity: { delay: 0.7, duration: 0.5 }, y: { delay: 1.1, duration: 7, repeat: Infinity, ease: "easeInOut" }, rotate: { delay: 1.1, duration: 9, repeat: Infinity, ease: "easeInOut" } }}',
  '        >',
  '          <svg width="56" height="56" viewBox="0 0 24 24" fill="none" className="text-green-700 drop-shadow-[0_6px_6px_rgba(0,0,0,0.22)]">',
  '            <path d="M12 2C6 2 2 7 2 12C2 18 12 22 12 22C12 22 22 18 22 12C22 7 18 2 12 2Z" fill="currentColor" />',
  '            <path d="M12 22V12" stroke="#4ade80" strokeWidth="0.8" strokeLinecap="round" />',
  '          </svg>',
  '        </motion.div>',
  '',
  '        {/* ── Decorative leaf: mid-left ── */}',
  '        <motion.div',
  '          className="absolute left-[0%] top-[52%] z-20 pointer-events-none"',
  '          initial={{ opacity: 0, rotate: -65 }}',
  '          animate={{ opacity: 1, rotate: [-65, -58, -65], x: [0, -3, 0] }}',
  '          transition={{ opacity: { delay: 0.85, duration: 0.5 }, x: { delay: 1.4, duration: 6.5, repeat: Infinity, ease: "easeInOut" } }}',
  '        >',
  '          <svg width="44" height="44" viewBox="0 0 24 24" fill="none" className="text-green-600 opacity-90 drop-shadow-[0_4px_4px_rgba(0,0,0,0.2)]">',
  '            <path d="M12 2C7 2 3 6 3 11C3 18 12 22 12 22C12 22 21 18 21 11C21 6 17 2 12 2Z" fill="currentColor" />',
  '          </svg>',
  '        </motion.div>',
  '',
  '        {/* ── Decorative leaf: lower-left foreground (partially cropped) ── */}',
  '        <motion.div',
  '          className="absolute left-[-5%] bottom-[8%] z-40 pointer-events-none"',
  '          initial={{ opacity: 0, rotate: 20 }}',
  '          animate={{ opacity: 1, rotate: [20, 26, 20], y: [0, 4, 0] }}',
  '          transition={{ opacity: { delay: 1.0, duration: 0.5 }, y: { delay: 1.5, duration: 6, repeat: Infinity, ease: "easeInOut" } }}',
  '        >',
  '          <svg width="80" height="80" viewBox="0 0 24 24" fill="none" className="text-green-800 drop-shadow-[0_10px_10px_rgba(0,0,0,0.3)] blur-[0.5px]">',
  '            <path d="M12 2C6 2 2 7 2 12C2 18 12 22 12 22C12 22 22 18 22 12C22 7 18 2 12 2Z" fill="currentColor" />',
  '            <path d="M12 22V12" stroke="#22c55e" strokeWidth="0.75" strokeLinecap="round" />',
  '          </svg>',
  '        </motion.div>',
  '',
  '        {/* ── Decorative leaf: right edge (partially cropped) ── */}',
  '        <motion.div',
  '          className="absolute right-[-6%] top-[60%] z-20 pointer-events-none"',
  '          initial={{ opacity: 0, rotate: 110 }}',
  '          animate={{ opacity: 1, rotate: [110, 104, 110], x: [0, 5, 0] }}',
  '          transition={{ opacity: { delay: 0.9, duration: 0.5 }, x: { delay: 1.6, duration: 6.5, repeat: Infinity, ease: "easeInOut" } }}',
  '        >',
  '          <svg width="65" height="65" viewBox="0 0 24 24" fill="none" className="text-green-700 drop-shadow-[0_8px_8px_rgba(0,0,0,0.25)] blur-[1px]">',
  '            <path d="M12 2C7 2 3 6 3 11C3 18 12 22 12 22C12 22 21 18 21 11C21 6 17 2 12 2Z" fill="currentColor" />',
  '          </svg>',
  '        </motion.div>',
  '',
  '        {/* ── Subtle bg blur leaf for depth ── */}',
  '        <motion.div',
  '          className="absolute left-[20%] bottom-[30%] z-10 pointer-events-none"',
  '          initial={{ opacity: 0, scale: 0.6 }}',
  '          animate={{ opacity: 0.5, scale: 0.6, y: [0, -4, 0] }}',
  '          transition={{ opacity: { delay: 1.1, duration: 0.5 }, y: { delay: 1.7, duration: 8, repeat: Infinity, ease: "easeInOut" } }}',
  '        >',
  '          <svg width="50" height="50" viewBox="0 0 24 24" fill="none" className="text-green-500 blur-[3px]">',
  '            <path d="M12 2C7 2 3 6 3 11C3 18 12 22 12 22C12 22 21 18 21 11C21 6 17 2 12 2Z" fill="currentColor" />',
  '          </svg>',
  '        </motion.div>',
  '',
  '      </div>',
  '    </div>',
  '  );',
  '}',
  '',
];

const replacement = lines.join('\n');
code = code.substring(0, s4vStart) + replacement + code.substring(s4vEnd);
fs.writeFileSync(file, code, 'utf8');
console.log('Successfully rebuilt Slide4Visual!');
