import { Post, StoryItem, RecipeCollection, NotificationItem, DirectMessageUser, Author } from './types';

export const CURRENT_USER: Author = {
  id: 'current_user_1',
  name: 'Alex Rivera',
  username: 'alex_foodcanvas',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  badge: 'Silver Spoon Cook',
  role: 'creator',
  followersCount: 342,
  recipesCount: 18,
};

export const INITIAL_STORIES: StoryItem[] = [
  {
    id: 'story_add',
    author: CURRENT_USER,
    imageUrl: '',
    caption: 'Share your dish!',
    timestamp: 'Just now',
  },
  {
    id: 'story_1',
    author: {
      id: 'author_elena',
      name: 'Elena Rostova',
      username: 'elena_bakes',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      badge: 'Pastry Pro',
      role: 'chef',
      followersCount: 6300,
      recipesCount: 52,
    },
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&auto=format&fit=crop&q=80',
    caption: 'Fresh sourdough scored with garlic rosemary butter! 🥖🍞',
    tag: '#SourdoughSunday',
    timestamp: '20m ago',
  },
  {
    id: 'story_2',
    author: {
      id: 'author_marcus',
      name: 'Chef Marcus Vance',
      username: 'marcus_flame',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      badge: 'Verified Chef',
      role: 'chef',
      followersCount: 12400,
      recipesCount: 84,
    },
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    caption: 'Prepping greens for the #SummerHarvestSalad challenge! 🥗💚',
    tag: '#SummerChallenge',
    timestamp: '1h ago',
  },
  {
    id: 'story_3',
    author: {
      id: 'author_hana',
      name: 'Hana Tanaka',
      username: 'hana_ramen',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      badge: 'Ramen Artisan',
      role: 'creator',
      followersCount: 4100,
      recipesCount: 39,
    },
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80',
    caption: '12-hour broth test simmering right now. Golden perfection! 🍜',
    tag: '#ComfortFood',
    timestamp: '2h ago',
  },
  {
    id: 'story_4',
    author: {
      id: 'author_carlos',
      name: 'Carlos Mendez',
      username: 'carlos_tacos',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      badge: 'Grill Master',
      role: 'user',
      followersCount: 980,
      recipesCount: 14,
    },
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&auto=format&fit=crop&q=80',
    caption: 'Smoked chipotle shrimp tacos with pickled red onions 🌮🔥',
    tag: '#TacoTuesday',
    timestamp: '4h ago',
  },
];

export const INITIAL_COMMUNITY_POSTS: Post[] = [
  {
    id: 'post_1',
    author: {
      id: 'chef_sofia',
      name: 'Chef Sofia Rossi',
      username: 'sofia_cooks',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      badge: 'Verified Chef',
      role: 'chef',
      followersCount: 8420,
      isFollowing: true,
      recipesCount: 64,
    },
    caption:
      'My signature Lemon Basil Pan-Seared Salmon with crispy skin and crushed pistachio gremolata. Cooked on medium-high in olive oil for that golden crunch! The secret is patting the fillet completely dry with paper towels before searing.',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=1000&auto=format&fit=crop&q=80',
    tags: ['#HealthyDinner', '#HighProtein', '#GlutenFree', '#Mediterranean', '#QuickDinner'],
    createdAt: '2 hours ago',
    likesCount: 384,
    isLiked: false,
    savesCount: 192,
    isSaved: false,
    commentsCount: 28,
    madeItCount: 47,
    hasMadeIt: false,
    rating: {
      overall: 4.9,
      flavor: 5.0,
      ease: 4.8,
      presentation: 4.9,
      totalReviews: 36,
    },
    recipe: {
      title: 'Crispy Lemon Basil Salmon & Pistachio Gremolata',
      cuisine: 'Mediterranean',
      difficulty: 'Medium',
      prepTimeMinutes: 10,
      cookTimeMinutes: 12,
      servings: 2,
      dietaryTags: ['High Protein', 'Gluten-Free', 'Keto Friendly', 'Omega-3'],
      nutrition: {
        calories: 480,
        protein: 42,
        carbs: 6,
        fat: 32,
        fiber: 2,
      },
      ingredients: [
        { name: 'Fresh Atlantic Salmon fillets', amount: '2 portions (6 oz each)' },
        { name: 'Fresh basil leaves, finely shredded', amount: '1/2 cup' },
        { name: 'Organic Lemon (zested & juiced)', amount: '1 whole' },
        { name: 'Roasted unsalted pistachios, crushed', amount: '3 tbsp' },
        { name: 'Extra virgin olive oil', amount: '2 tbsp' },
        { name: 'Flaky Maldon sea salt & cracked black pepper', amount: 'to taste' },
        { name: 'Fresh garlic clove, microplaned', amount: '1 clove', optional: true },
      ],
      steps: [
        {
          stepNumber: 1,
          instruction: 'Pat salmon skin and flesh completely dry with paper towels. Season generously with kosher salt and black pepper on both sides.',
          durationMinutes: 3,
          tip: 'Moisture is the enemy of crispy skin!',
        },
        {
          stepNumber: 2,
          instruction: 'Mix chopped basil, crushed pistachios, lemon zest, garlic, and 1 tbsp olive oil in a small bowl to form the gremolata.',
          durationMinutes: 3,
        },
        {
          stepNumber: 3,
          instruction: 'Heat remaining olive oil in a stainless steel or cast iron skillet over medium-high heat until shimmering. Place salmon skin-side down and press gently for 10 seconds.',
          durationMinutes: 5,
          tip: 'Do not move the fish for 4 minutes to allow an even crust to develop.',
        },
        {
          stepNumber: 4,
          instruction: 'Flip and sear the flesh side for 2 minutes for medium doneness. Transfer to warm plates and spoon pistachio gremolata over the top with a fresh squeeze of lemon juice.',
          durationMinutes: 2,
        },
      ],
    },
    reviews: [
      {
        id: 'rev_1',
        userId: 'u_david',
        userName: 'David Miller',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        userBadge: 'Home Cook',
        rating: 5,
        flavorRating: 5,
        easeRating: 5,
        presentationRating: 5,
        comment: 'Made this tonight for dinner and my partner loved it! The pistachio crunch is pure restaurant quality.',
        cookingTips: 'I used a cast iron skillet and got the crispiest skin ever.',
        createdAt: '45m ago',
        likesCount: 12,
        isLiked: true,
      },
      {
        id: 'rev_2',
        userId: 'u_sarah',
        userName: 'Sarah Jenkins',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        flavorRating: 5,
        easeRating: 4,
        presentationRating: 5,
        comment: 'Super fast weeknight meal. Flavors are so bright and clean.',
        createdAt: '1h ago',
        likesCount: 5,
      },
    ],
    comments: [
      {
        id: 'com_1',
        userId: 'u_clara',
        userName: 'Clara Chen',
        userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
        content: 'That sear looks incredible Sofia! What oil smoke point do you recommend?',
        createdAt: '1h ago',
        likesCount: 4,
      },
    ],
  },
  {
    id: 'post_2',
    author: {
      id: 'chef_liam',
      name: 'Liam Vance',
      username: 'vance_kitchen',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      badge: 'Pasta Master',
      role: 'creator',
      followersCount: 5210,
      isFollowing: false,
      recipesCount: 41,
    },
    caption:
      'Creamy Tuscan Garlic Butter Sun-Dried Tomato Gnocchi. Silky sauce made with heavy cream, white wine, baby spinach, and aged parmesan. Ready in under 20 minutes!',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=1000&auto=format&fit=crop&q=80',
    tags: ['#ComfortFood', '#Gnocchi', '#ItalianEats', '#Vegetarian', '#QuickMeals'],
    createdAt: '4 hours ago',
    likesCount: 512,
    isLiked: true,
    savesCount: 318,
    isSaved: true,
    commentsCount: 42,
    madeItCount: 89,
    hasMadeIt: true,
    rating: {
      overall: 4.8,
      flavor: 5.0,
      ease: 4.9,
      presentation: 4.7,
      totalReviews: 54,
    },
    recipe: {
      title: '20-Min Creamy Tuscan Sun-Dried Tomato Gnocchi',
      cuisine: 'Italian',
      difficulty: 'Easy',
      prepTimeMinutes: 5,
      cookTimeMinutes: 15,
      servings: 3,
      dietaryTags: ['Vegetarian', 'Quick Dinner', 'Comfort Food'],
      nutrition: {
        calories: 520,
        protein: 14,
        carbs: 58,
        fat: 26,
        fiber: 4,
      },
      ingredients: [
        { name: 'Potato gnocchi (shelf-stable or fresh)', amount: '500g (1 lb)' },
        { name: 'Sun-dried tomatoes in oil, julienned', amount: '1/2 cup' },
        { name: 'Fresh baby spinach', amount: '3 packed cups' },
        { name: 'Heavy cooking cream', amount: '3/4 cup' },
        { name: 'Vegetable broth or dry white wine', amount: '1/3 cup' },
        { name: 'Minced garlic', amount: '4 cloves' },
        { name: 'Freshly grated Parmigiano-Reggiano', amount: '1/2 cup' },
        { name: 'Red pepper chili flakes', amount: '1/2 tsp', optional: true },
      ],
      steps: [
        {
          stepNumber: 1,
          instruction: 'Boil gnocchi in salted water for 2-3 minutes until they float to the surface. Drain and reserve 1/4 cup pasta water.',
          durationMinutes: 4,
        },
        {
          stepNumber: 2,
          instruction: 'In a large skillet, heat 1 tbsp oil from sun-dried tomatoes. Sauté garlic, chili flakes, and sun-dried tomatoes for 1 minute until fragrant.',
          durationMinutes: 2,
        },
        {
          stepNumber: 3,
          instruction: 'Pour in white wine and cream, bring to a gentle simmer for 3 minutes. Stir in baby spinach until wilted.',
          durationMinutes: 4,
        },
        {
          stepNumber: 4,
          instruction: 'Toss in boiled gnocchi and grated parmesan. Stir until sauce clings luxuriously to each dumpling.',
          durationMinutes: 3,
        },
      ],
    },
    reviews: [],
    comments: [
      {
        id: 'com_2',
        userId: 'u_maya',
        userName: 'Maya Lin',
        userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
        content: 'I made this with store-bought gluten free gnocchi and it was heavenly! 🌟',
        createdAt: '2h ago',
        likesCount: 8,
      },
    ],
  },
  {
    id: 'post_3',
    author: {
      id: 'chef_amara',
      name: 'Amara Okafor',
      username: 'amara_plants',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      badge: 'Plant-Based Pioneer',
      role: 'creator',
      followersCount: 11200,
      isFollowing: true,
      recipesCount: 78,
    },
    caption:
      'Rainbow Nourish Bowl with crispy maple tahini chickpeas, massaged kale, roasted sweet potatoes, and avocado rose. Fuel your week right! 🥑🌈',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=1000&auto=format&fit=crop&q=80',
    tags: ['#VeganBowl', '#PlantBased', '#MealPrep', '#SummerChallenge', '#CleanEating'],
    createdAt: '6 hours ago',
    likesCount: 620,
    isLiked: false,
    savesCount: 410,
    isSaved: false,
    commentsCount: 35,
    madeItCount: 104,
    hasMadeIt: false,
    isChallengeEntry: true,
    challengeName: 'Summer Harvest Salad Challenge',
    rating: {
      overall: 4.9,
      flavor: 4.9,
      ease: 5.0,
      presentation: 5.0,
      totalReviews: 68,
    },
    recipe: {
      title: 'Maple Tahini Rainbow Chickpea Nourish Bowl',
      cuisine: 'Global Health',
      difficulty: 'Easy',
      prepTimeMinutes: 15,
      cookTimeMinutes: 20,
      servings: 2,
      dietaryTags: ['Vegan', 'Gluten-Free', 'High Fiber', 'Dairy-Free'],
      nutrition: {
        calories: 440,
        protein: 16,
        carbs: 62,
        fat: 17,
        fiber: 14,
      },
      ingredients: [
        { name: 'Canned organic chickpeas, rinsed and dried', amount: '1 can (15 oz)' },
        { name: 'Sweet potato, cubed', amount: '1 medium' },
        { name: 'Curly kale, stems removed & chopped', amount: '4 cups' },
        { name: 'Ripe Hass avocado', amount: '1 whole' },
        { name: 'Runny sesame tahini', amount: '3 tbsp' },
        { name: 'Pure maple syrup', amount: '1 tbsp' },
        { name: 'Lemon juice & warm water', amount: '2 tbsp each' },
      ],
      steps: [
        {
          stepNumber: 1,
          instruction: 'Toss sweet potatoes and chickpeas with 1 tbsp olive oil, smoked paprika, and salt. Roast at 400°F (200°C) for 20 minutes.',
          durationMinutes: 20,
        },
        {
          stepNumber: 2,
          instruction: 'Massage chopped kale with 1 tsp olive oil and a pinch of sea salt for 2 minutes until tender and deep green.',
          durationMinutes: 2,
        },
        {
          stepNumber: 3,
          instruction: 'Whisk tahini, maple syrup, lemon juice, salt, and warm water until silky and pourable.',
          durationMinutes: 2,
        },
        {
          stepNumber: 4,
          instruction: 'Assemble bowls with massaged kale base, roasted sweet potatoes, crispy chickpeas, sliced avocado, and drizzle with maple tahini dressing.',
          durationMinutes: 3,
        },
      ],
    },
    reviews: [],
    comments: [],
  },
];

export const INITIAL_COLLECTIONS: RecipeCollection[] = [
  {
    id: 'col_1',
    name: 'Quick 20-Min Dinners',
    description: 'Effortless weeknight recipes with minimal prep and cleanup.',
    coverImage: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80',
    recipeCount: 12,
  },
  {
    id: 'col_2',
    name: 'High-Protein Wellness',
    description: 'Post-workout fuel and macronutrient-balanced power bowls.',
    coverImage: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
    recipeCount: 18,
  },
  {
    id: 'col_3',
    name: 'Weekend Baking & Sourdough',
    description: 'Artisan breads, scored boules, focaccia, and pastries.',
    coverImage: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    recipeCount: 7,
  },
];

export const TOP_CHEFS_TO_FOLLOW: Author[] = [
  {
    id: 'chef_sofia',
    name: 'Chef Sofia Rossi',
    username: 'sofia_cooks',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    badge: 'Verified Chef',
    role: 'chef',
    followersCount: 8420,
    isFollowing: true,
    recipesCount: 64,
  },
  {
    id: 'chef_marcus',
    name: 'Chef Marcus Vance',
    username: 'marcus_flame',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    badge: 'Grill Specialist',
    role: 'chef',
    followersCount: 12400,
    isFollowing: false,
    recipesCount: 84,
  },
  {
    id: 'chef_amara',
    name: 'Amara Okafor',
    username: 'amara_plants',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    badge: 'Plant-Based Pro',
    role: 'creator',
    followersCount: 11200,
    isFollowing: true,
    recipesCount: 78,
  },
  {
    id: 'chef_elena',
    name: 'Elena Rostova',
    username: 'elena_bakes',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    badge: 'Pastry Master',
    role: 'chef',
    followersCount: 6300,
    isFollowing: false,
    recipesCount: 52,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    type: 'like',
    user: TOP_CHEFS_TO_FOLLOW[0],
    text: 'liked your Lemon Basil Salmon recipe post',
    timeAgo: '10m ago',
    read: false,
  },
  {
    id: 'notif_2',
    type: 'review',
    user: TOP_CHEFS_TO_FOLLOW[1],
    text: 'gave 5 stars ★ to your Sourdough scoring technique',
    timeAgo: '45m ago',
    read: false,
  },
  {
    id: 'notif_3',
    type: 'challenge',
    user: TOP_CHEFS_TO_FOLLOW[2],
    text: 'submitted a dish in the #SummerHarvestSalad challenge',
    timeAgo: '2h ago',
    read: true,
  },
];

export const INITIAL_DM_CONTACTS: DirectMessageUser[] = [
  {
    id: 'dm_1',
    name: 'Chef Sofia Rossi',
    username: 'sofia_cooks',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    online: true,
    lastMessage: 'Let me know how the salmon pan-sear turned out!',
    lastMessageTime: '12m ago',
    unreadCount: 1,
  },
  {
    id: 'dm_2',
    name: 'Marcus Vance',
    username: 'marcus_flame',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    online: false,
    lastMessage: 'Here is the dry rub seasoning proportion 🥩',
    lastMessageTime: '3h ago',
  },
  {
    id: 'dm_3',
    name: 'Elena Rostova',
    username: 'elena_bakes',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    online: true,
    lastMessage: 'Sourdough starter feeding schedule sent!',
    lastMessageTime: 'Yesterday',
  },
];
